# Default values for helloworld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: asamba/hiworld
  tag: v1
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080

containerPort:
  port: 8080